on:
  push:
    branches: [main]
  pull_request:

name: CI

jobs:
  flake8:
    name: Linter
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt -y install flake8
      - name: Lint with flake8
        run: |
          flake8 --builtins=_ --ignore E402,W503 --max-complexity=10 --max-line-length=110 --show-source --statistics src/

  mypy:
    name: Static Type Checker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt -y install mypy
      - name: Check with MyPy
        run: |
          mypy --ignore-missing-imports --disallow-incomplete-defs src

  typos:
    name: Typos
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check for typos
        uses: crate-ci/typos@master

  flatpak:
    name: Flatpak
    runs-on: ubuntu-22.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: breathing.flatpak
          manifest-path: io.github.seadve.Breathing.json
          run-tests: true
          cache-key: flatpak-builder-${{ github.sha }}
